"""Provider-neutral identity, membership, and workspace authorization seam."""

from pulseiq.postgres import DatabaseScope

from .adapters import InMemoryMembershipRepository, InMemorySessionRepository
from .administration import IdentityAdministrationService, MembershipAdministrationError
from .authorization import AuthorizationService
from .contracts import (
    AcceptWorkspaceInvitation,
    AuthenticatedActor,
    AuthorizationDecision,
    AuthorizationPolicy,
    AuthorizationRequest,
    ChangeMembershipRole,
    InvitationAcceptanceResult,
    InvitationIssueResult,
    InvitationStatus,
    InviteWorkspaceMember,
    Membership,
    MembershipChangeResult,
    MembershipStatus,
    Permission,
    ResourceScope,
    RevokeMembership,
    RevokeSession,
    Role,
    SessionRecord,
    SessionRevocationResult,
    SessionStatus,
    WorkspaceInvitation,
)
from .invitations import IdentityInvitationService, InvitationError
from .oidc import (
    AuthenticationEvent,
    InMemoryOidcLoginRepository,
    OidcLoginError,
    OidcLoginResult,
    OidcLoginService,
    OidcLoginStart,
    OidcLoginTransaction,
    OidcProviderPolicy,
    OidcTransactionStatus,
    OidcVerificationError,
    OidcVerifiedIdentity,
)
from .postgres import PostgresIdentityRepository
from .sessions import SessionAdministrationError, SessionAdministrationService
from .web import (
    BrowserAuthenticationError,
    BrowserRequestAuthenticator,
    BrowserSessionCodec,
    BrowserSessionEnvelope,
    BrowserSessionKey,
    BrowserSessionPolicy,
    RequestIntegrityError,
)

__all__ = [
    "AcceptWorkspaceInvitation",
    "AuthenticatedActor",
    "AuthenticationEvent",
    "AuthorizationDecision",
    "AuthorizationPolicy",
    "AuthorizationRequest",
    "AuthorizationService",
    "BrowserAuthenticationError",
    "BrowserRequestAuthenticator",
    "BrowserSessionCodec",
    "BrowserSessionEnvelope",
    "BrowserSessionKey",
    "BrowserSessionPolicy",
    "ChangeMembershipRole",
    "DatabaseScope",
    "IdentityAdministrationService",
    "IdentityInvitationService",
    "InMemoryMembershipRepository",
    "InMemoryOidcLoginRepository",
    "InMemorySessionRepository",
    "InvitationAcceptanceResult",
    "InvitationError",
    "InvitationIssueResult",
    "InvitationStatus",
    "InviteWorkspaceMember",
    "Membership",
    "MembershipAdministrationError",
    "MembershipChangeResult",
    "MembershipStatus",
    "OidcLoginError",
    "OidcLoginResult",
    "OidcLoginService",
    "OidcLoginStart",
    "OidcLoginTransaction",
    "OidcProviderPolicy",
    "OidcTransactionStatus",
    "OidcVerificationError",
    "OidcVerifiedIdentity",
    "Permission",
    "PostgresIdentityRepository",
    "RequestIntegrityError",
    "ResourceScope",
    "RevokeMembership",
    "RevokeSession",
    "Role",
    "SessionAdministrationError",
    "SessionAdministrationService",
    "SessionRecord",
    "SessionRevocationResult",
    "SessionStatus",
    "WorkspaceInvitation",
]
